# Site settings
title: Toxoplasma Pre-conference Workshop
email: beiting@vet.upenn.edu and oharb@sas.upenn.edu
description: > # this means to ignore newlines until "baseurl:"
  The website for the Toxoplasma Pre-conference Workshop
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ToxoGenomicsWorkshop.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  

# Build settings
markdown: kramdown
