# Site settings
title: Toxoplasma Pre-conference Genomics Workshop - RNAseq data analysis
email: beiting@vet.upenn.edu and oharb@sas.upenn.edu
description: > # this means to ignore newlines until "baseurl:"
  The website for the Toxoplasma , taught by Dan Beiting and Omar Harb in the Summer of 2015.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ToxoGenomicsWorkshop.github.io" # the base hostname & protocol for your site
twitter_username: hostmicrobe
github_username:  dpbisme

# Build settings
markdown: kramdown
